name: C/C++ CI/CD Pipeline

on: 
  pull_request:
    branch: 
      - main

jobs:
  ubuntu-build:
    runs-on: ubuntu-24.04
    steps: 
      - name: Update apt package list & install g++-14
        run: |
          sudo apt-get update
          sudo apt install g++-14 gcc-14 -y

      - name: Set g++-14 as default compiler
        run: |
          echo "CXX=g++-14" >> $GITHUB_ENV
          echo "CC=gcc-14" >> $GITHUB_ENV
      
      - name: Checkout 
        uses: actions/checkout@v4
      
      - name: Install conan
        uses: conan-io/setup-conan@v1
        with:
          cache_packages: true
          profile_detect: false

      - name: Install Conan dependencies
        run: conan install . --build=missing -pr:h=profiles/profile_linux_x86 -pr:b=profiles/profile_linux_x86

      - name: Build tests
        shell: bash
        run: |
          cmake --preset conan-release
          cmake --build --preset conan-release

      - name: Run tests
        run: ./build/Release/tests/test

